
#订单表
CREATE TABLE `t_order` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `buyer_id` bigint(50) DEFAULT NULL COMMENT '买家id',
  `order_no` varchar(50) NOT NULL COMMENT '订单号',
  `parent_order_no` varchar(50) DEFAULT NULL COMMENT '父订单号',
  `order_no_out` varchar(50) DEFAULT NULL COMMENT '外部系统订单号',
  `trade_type` int(11) unsigned NOT NULL COMMENT '交易类型',
  `trade_status` tinyint(11) NOT NULL DEFAULT '1' COMMENT '交易状态 0-订单取消,1-待付款,3-待发货,5-已发货,8-订单成功,9-已关闭',
  `channel` varchar(20) DEFAULT NULL COMMENT '渠道',
  `payment_time` datetime DEFAULT NULL COMMENT '支付时间',
  `amount` decimal(18,2) DEFAULT NULL COMMENT '实际支付金额',
  `orgin_amount` decimal(18,2) DEFAULT NULL COMMENT '订单原始金额',
  `delivery_fee` decimal(18,2) DEFAULT '0.00' COMMENT '运费',
  `actual_amount` decimal(18,2) DEFAULT NULL COMMENT '实际金额',
  `discount_price` decimal(18,2) DEFAULT NULL COMMENT '优惠金额',
  `device_id` varchar(50) DEFAULT NULL COMMENT '订单生成设备标示',
  `is_reverse` tinyint(11) DEFAULT '0' COMMENT '是否售后 0-不是,1-是',
  `ext_data` text COMMENT '扩展信息',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` varchar(20) DEFAULT NULL COMMENT '创建人',
  `modifier` varchar(20) DEFAULT NULL COMMENT '更新人',
  `is_deleted` tinyint(6) DEFAULT '0' COMMENT '是否逻辑删除：0-否，1-是',
  `order_receive_time` datetime DEFAULT NULL COMMENT '收货时间',
  `order_logistics_time` datetime DEFAULT NULL COMMENT '发货时间',
  `is_parent` int(11) DEFAULT '0' COMMENT '是否是父单  1.是  0.不是',
  `cancel_reason_desc` varchar(255) DEFAULT NULL COMMENT '取消原因描述',
  `cancel_type` int(11) DEFAULT NULL COMMENT '取消类型 1、用户取消  2、系统取消 3、客服取消',
  `cancel_operate_id` int(11) DEFAULT NULL COMMENT '取消操作人id',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `cancel_reason_id` int(11) DEFAULT NULL COMMENT '取消订单原因id',
  `ext_param` json DEFAULT NULL COMMENT '扩展json 用于存储 添加的字段',
  `is_show` tinyint(6) DEFAULT '1' COMMENT 'C端是否显示，1 显示  0 不显示',
  `payment_status` tinyint(4) DEFAULT NULL COMMENT '支付状态（0未支付   1部分支付  2已支付）',
  `close_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '订单关闭时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_order_no` (`order_no`) USING BTREE,
  KEY `idx_create_time` (`create_time`),
  KEY `idx_payment_time` (`payment_time`),
  KEY `idx_update_time` (`update_time`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='订单表';


#订单明细表
CREATE TABLE `t_order_line` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_id` bigint(20) NOT NULL COMMENT '订单主键id',
  `sku_id` bigint(20) DEFAULT NULL COMMENT 'sku id',
  `sku_price` decimal(18,2) DEFAULT NULL COMMENT 'sku价格（成本价格）',
  `item_type` varchar(11) DEFAULT NULL COMMENT '商品类型',
  `is_gift` tinyint(11) DEFAULT '2' COMMENT '是否赠品 1-赠品,2-不是',
  `actual_price` decimal(18,2) DEFAULT NULL COMMENT '实际价格(销售价格)',
  `sku_quantity` decimal(18,3) DEFAULT NULL COMMENT 'sku购买数量',
  `discount_price` decimal(18,2) DEFAULT NULL COMMENT '优惠价格',
  `paid_price` decimal(18,2) DEFAULT NULL COMMENT '实付价格',
  `vip_price` decimal(18,2) DEFAULT NULL COMMENT '会员价格',
  `sales_unit` varchar(20) DEFAULT NULL COMMENT '销售单位',
  `ext_data` text COMMENT '扩展信息',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` varchar(20) DEFAULT NULL COMMENT '创建人',
  `modifier` varchar(20) DEFAULT NULL COMMENT '更新人',
  `is_deleted` tinyint(6) DEFAULT '0' COMMENT '是否逻辑删除：0-否，1-是',
  `version_no` int(11) DEFAULT '0' COMMENT '版本号:默认0,每次更新+1',
  `channel` varchar(20) DEFAULT NULL COMMENT '渠道',
  `channel_code` varchar(50) DEFAULT NULL COMMENT '渠道code',
  `sku_code` varchar(10) DEFAULT NULL COMMENT 'skuCode',
  `sales_unit_name` varchar(20) DEFAULT NULL COMMENT 'unit code',
  `parent_sku_code` varchar(100) DEFAULT NULL COMMENT '如果是组合品子品 则是 父明细skucode ',
  `order_line_no` varchar(30) DEFAULT NULL COMMENT '行号',
  `sku_name` varchar(255) DEFAULT NULL,
  `pic_path` varchar(255) DEFAULT NULL,
  `category_id` bigint(20) DEFAULT NULL COMMENT '类目id',
  `category_name` varchar(255) DEFAULT NULL COMMENT '类目名称',
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_sku_code_sales_unit` (`sku_code`,`sales_unit`),
  KEY `idx_update_time` (`update_time`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='订单明细表';

#订单商品明细表
CREATE TABLE `t_order_product_line` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_line_id` bigint(20) DEFAULT NULL COMMENT '订单明细id',
  `sku_id` bigint(20) DEFAULT NULL COMMENT 'sku id',
  `product_pic_path` varchar(300) DEFAULT NULL COMMENT '产品图片URL',
  `product_version_no` bigint(18) DEFAULT NULL COMMENT '产品信息version',
  `product_cname` varchar(1000) DEFAULT NULL COMMENT '产品中文名',
  `product_ename` varchar(1024) DEFAULT NULL COMMENT '产品英文名',
  `product_gross_weight` decimal(18,3) DEFAULT NULL COMMENT '产品毛重',
  `brand_id` bigint(20) DEFAULT NULL COMMENT '品牌id',
  `brand_name` varchar(512) DEFAULT NULL COMMENT '品牌名称',
  `category_id` bigint(20) DEFAULT NULL COMMENT '类目id',
  `category_name` varchar(512) DEFAULT NULL COMMENT '类目名称',
  `ext_data` text COMMENT '扩展信息',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` varchar(20) DEFAULT NULL COMMENT '创建人',
  `modifier` varchar(20) DEFAULT NULL COMMENT '更新人',
  `is_deleted` tinyint(6) DEFAULT '0' COMMENT '是否逻辑删除：0-否，1-是',
  `version_no` int(11) DEFAULT '0' COMMENT '版本号:默认0,每次更新+1',
  `order_no` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_order_line_id` (`order_line_id`),
  KEY `idx_product_cname` (`product_cname`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='订单商品明细表';

#订单地址表
CREATE TABLE `t_order_address` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_no` varchar(50) NOT NULL COMMENT '订单号',
  `parent_order_code` varchar(50) DEFAULT '' COMMENT '订单号',
  `good_receiver_address` varchar(400) DEFAULT NULL COMMENT '收货人地址',
  `good_receiver_postcode` varchar(200) DEFAULT NULL,
  `good_receiver_name` varchar(100) DEFAULT NULL COMMENT '收货人姓名',
  `good_receiver_first_name` varchar(100) DEFAULT NULL COMMENT '收货人名',
  `good_receiver_last_name` varchar(100) DEFAULT NULL COMMENT '收货人姓',
  `good_receiver_mobile` varchar(50) DEFAULT NULL COMMENT '收货人手机',
  `good_receiver_country_id` bigint(18) DEFAULT NULL COMMENT '收货人国家ID',
  `good_receiver_country` varchar(100) DEFAULT NULL COMMENT '收货人国家',
  `good_receiver_province_id` bigint(18) DEFAULT NULL COMMENT '收货人省份ID',
  `good_receiver_province` varchar(50) DEFAULT NULL COMMENT '收货人省份',
  `good_receiver_city_id` bigint(18) DEFAULT NULL COMMENT '收货人城市ID',
  `good_receiver_city` varchar(100) DEFAULT NULL COMMENT '收货人城市',
  `good_receiver_area_id` bigint(18) DEFAULT NULL COMMENT '收货人四级区域ID',
  `good_receiver_area` varchar(100) DEFAULT NULL COMMENT '收货人四级区域',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` varchar(20) DEFAULT NULL COMMENT '创建人',
  `modifier` varchar(20) DEFAULT NULL COMMENT '更新人',
  `is_deleted` tinyint(6) DEFAULT '0' COMMENT '是否逻辑删除：0-否，1-是',
  `version_no` int(11) DEFAULT '0' COMMENT '版本号:默认0,每次更新+1',
  `ext_data` text COMMENT '扩展信息',
  PRIMARY KEY (`id`),
  KEY `idx_order_no` (`order_no`) USING BTREE,
  KEY `idx_good_receiver_mobile` (`good_receiver_mobile`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_good_receiver_name` (`good_receiver_name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='订单收货地址表';